version: "3.8"

services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root


  springapp:
    depends_on:
      - mysql
    build: .
    image: mikeqiu2011/springapp
    ports:
      - "30002:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/db_example"
      }'
#    volumes:
#      - ~/.m2:/root/.m2



  webserver:
    build: ./frontend
    image: mikeqiu2011/webserver
    ports:
      - "30001:80"