apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: springapp
  name: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: springapp
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.datasource.url": "jdbc:mysql://mysql:3306/db_example" }'
          image: mikeqiu2011/springapp
          name: springapp
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
