apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: springapp
  name: springapp
spec:
  ports:
    - name: "30002"
      port: 30002
      nodePort: 30002
      targetPort: 8080
  selector:
    io.kompose.service: springapp
  type: NodePort
status:
  loadBalancer: {}
